### ISSUE TITLE
Can you add a LICENSE[.txt, .md] please?

### ISSUE THREAD

**Issue by SebastianRiedel** [strawlab/bag2hdf5#4]
Preferably something permissive, e.g. like ROS core (from http://www.ros.org/is-ros-for-me/):

> The core of ROS is licensed under the standard three-clause BSD license. This is a very permissive open license that allows for reuse in commercial and closed source products.

General info: https://help.github.com/articles/licensing-a-repository/

**Comment by StohanzlMart** [comment]
+1

**Comment by astraw** [comment]
Sorry I missed this originally. Fixed now.

**Comment by StohanzlMart** [comment]
Thank you Saint astraw!
